# Imports

In [3]:
from numpy.random import seed
seed(888)
import tensorflow as tf
tf.random.set_seed(404)

In [36]:
import tensorflow.compat.v1 as tf1
tf1.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
import os
import numpy as np

from time import strftime
from PIL import Image

# Constants

In [5]:
X_TRAIN_PATH = 'MNIST/digit_xtrain.csv'
X_TEST_PATH = 'MNIST/digit_xtest.csv'
Y_TRAIN_PATH = 'MNIST/digit_ytrain.csv'
Y_TEST_PATH = 'MNIST/digit_ytest.csv'

In [34]:
NR_CLASSES = 10
VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_WIDTH*IMAGE_HEIGHT*CHANNELS

# Get the Data

In [19]:
x_train_all = np.loadtxt(X_TRAIN_PATH,delimiter=',',dtype=int)
y_train_all = np.loadtxt(Y_TRAIN_PATH,delimiter=',',dtype=int)
x_test = np.loadtxt(X_TEST_PATH,delimiter=',',dtype=int)
y_test = np.loadtxt(Y_TEST_PATH,delimiter=',',dtype=int)

In [20]:
print(f'x_train_all shape {x_train_all.shape}')
print(f'y_train_all shape {y_train_all.shape}')
print(f'x_test shape {x_test.shape}')
print(f'y_test shape {y_test.shape}')

x_train_all shape (60000, 784)
y_train_all shape (60000,)
x_test shape (10000, 784)
y_test shape (10000,)


In [21]:
y_test

array([7, 2, 1, ..., 4, 5, 6])

# Data Pre-processing

In [22]:
x_train_all,x_test = x_train_all/255.0, x_test/255.0

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.eye(NR_CLASSES)[2]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.eye(NR_CLASSES)[y_train_all]

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [26]:
y_train_all = np.eye(NR_CLASSES)[y_train_all]

In [27]:
y_train_all.shape

(60000, 10)

In [28]:
y_test = np.eye(NR_CLASSES)[y_test]
y_test.shape

(10000, 10)

In [30]:
x_val = x_train_all[:VALIDATION_SIZE]
y_val = y_train_all[:VALIDATION_SIZE]
x_test = x_train_all[VALIDATION_SIZE:]
y_test = y_train_all[VALIDATION_SIZE:]

In [32]:
x_val.shape

(10000, 784)

In [33]:
x_test.shape

(50000, 784)

# Setup Tensorflow Graph

In [37]:
X = tf1.placeholder(tf1.float32,shape=[None,TOTAL_INPUTS])
y = tf1.placeholder(tf1.float32,shape=[None,NR_CLASSES])